#### general settings
name: MYNET
use_tb_logger: true

#### datasets
datasets:
  name: RWF
  train: /home/ymkim/test/Violence_Detection/datasets/train
  valid: /home/ymkim/test/Violence_Detection/datasets/val
  test: /home/ymkim/test/Violence_Detection/datasets/val
  stride: -1
  

dataloader:
  train:
    batch_size: 8
    shuffle: true
    # pin_memeory: true
    num_workers: 0

  valid:
    batch_size: 1
    shuffle: true
    # pin_memeory: true
    num_workers: 0

  test:
    batch_size: 1
    shuffle: false
    # pin_memeory: true
    num_workers: 0


#### network structures
MYNET:
  sequence_size: 31 # Temporal duration of input clip

trainer:
  epochs: 20
  device: 0,1
  save_path: /home/ymkim/test/Violence_Detection
  #ckpt_path: /home/nas/user/minseok/exp/GLOTIS_model65/RWF/18October_1101/ckpt/best.pt
  comment: gray

tester:
  ckpt_path: ./ckpt/RWF/617_3.3689.pt
  device: 0


criterion:
  name: CrossEntropy

optimizer:
  name: Adam #RMSprop #RAdam   ### Adam, RMSprop, SGD
  lr: !!float 1e-3
  # betas: (0.9, 0.999)
  eps: !!float 1e-9
  weight_decay: !!float 1e-2

scheduler:
  name: cycle
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
